### ISSUE TITLE
OSRM-bench mark first go

### ISSUE THREAD

**Issue by rafavdz** [ITSLeeds/routingday#7]
This focuses on setting a basic local OSRM server using the default bicycle profile. Anyone is free to go further to potentially explore the modification of profiles.

**Comment by Robinlovelace** [comment]
Sounds good!

**Comment by rafavdz** [comment]
The changes for setting up and benchmarking the local OSRM server have been committed directly to the main branch. You can view the commit here: [b8d8929](https://github.com/ITSLeeds/routingday/commit/b8d8929).

**Comment by Robinlovelace** [comment]
👍
